/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClinicReservationSystem;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar Kamal
 */
public class HomePage extends javax.swing.JFrame {

    
    
    
    public static String getUsername1() {
        return Username1;
    }

    public static void setUsername1(String Username1) {
        HomePage.Username1 = Username1;
    }

    

    private static String Username1="Omar Kamal";
    static Toolkit tk= Toolkit.getDefaultToolkit();
    static int  xsize=(int) tk.getScreenSize().getWidth();
    static int  ysize=(int) tk.getScreenSize().getHeight();
    /**
     * Creates new form HomePage
     */
    
    public HomePage() {
        this.setUndecorated(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Clinic.LoadingDataBase();
        this.setSize(xsize, ysize);
        Background.setSize(xsize, ysize);
        ImageIcon icon=new ImageIcon ("r.jpg");
        Image img=icon.getImage();
        Image newimg = img.getScaledInstance(Background.getWidth(), Background.getHeight(),  java.awt.Image.SCALE_SMOOTH ) ;  
        icon=new ImageIcon(newimg);
        Background.setIcon(icon);
        jPanel1.setBackground(new Color(51,51,255,10));
        buttonGroup1.add(ClientRadio);
        buttonGroup1.add(StaffRadio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TuserName = new javax.swing.JTextField();
        Tpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        StaffRadio = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ClientRadio = new javax.swing.JRadioButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel3.setText("Clinic Reservation System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 33, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("UserName");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 80, 91, 29));

        TuserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuserNameActionPerformed(evt);
            }
        });
        TuserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TuserNameKeyTyped(evt);
            }
        });
        jPanel1.add(TuserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 86, 136, -1));
        jPanel1.add(Tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 124, 136, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 120, 78, 25));

        StaffRadio.setText("Doctor");
        StaffRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffRadioActionPerformed(evt);
            }
        });
        jPanel1.add(StaffRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 163, -1, -1));

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 111, -1));

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 73, -1));

        jButton4.setText("Login as a Guest");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 245, -1, -1));

        ClientRadio.setText("Patient");
        jPanel1.add(ClientRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 480, 290));

        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TuserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuserNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         if(TuserName.getText().trim().length()==0)
                {
                    JOptionPane.showMessageDialog(null, "Please Enter Your Username");
                }
             else if(Tpassword.getText().trim().length()==0)
                {
                    JOptionPane.showMessageDialog(null, "Please Enter Your Password");
                }
             else{
                    if(StaffRadio.isSelected())
                    {
                                if(Doctor.login(TuserName.getText(),Tpassword.getText()))
                                {
                                        Username1=TuserName.getText();
                                        DoctorHome fr2=new DoctorHome();
                                        fr2.setVisible(true);
                                        this.setVisible(false);
                                        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
                                }

                    }
                    else if(ClientRadio.isSelected())
                    {
                        if(Patient.login(TuserName.getText(),Tpassword.getText()))
                        {
                            Username1=TuserName.getText();

                                PatientHome fr2=new PatientHome();
                                fr2.setVisible(true);
                                this.setVisible(false);
                                this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);


                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Choose Staff or Client");
                        Username1="F";
                    }
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            CreateAccount fr2=new CreateAccount();
            this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
            fr2.setVisible(true);
            this.setVisible(false);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                    Username1="F";
                    PatientHome fr2=new PatientHome();
                    fr2.setVisible(true);
                    this.setVisible(false);
                    this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
               
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StaffRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffRadioActionPerformed

    private void TuserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TuserNameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if((c==KeyEvent.VK_SPACE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TuserNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JRadioButton ClientRadio;
    private javax.swing.JRadioButton StaffRadio;
    private javax.swing.JPasswordField Tpassword;
    private javax.swing.JTextField TuserName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
